export enum BannedCause {
    CHEAT = 'CHEAT',
    RULE_VIOLATION = 'RULE_VIOLATION',
    DISRUPTIVE_BEHAVIOR = 'DISRUPTIVE_BEHAVIOR',
    ATTENDANCE_ISSUE = 'ATTENDANCE_ISSUE',
    OTHER = 'OTHER',
}
